message: message from test property file
my.list.values: one,two,three,four,five
mapvalues: "{first:'value1',second:'value2',third:'value3',four:'value4'}"
testing:
   listvalues: one,two,three,four,five
   mapvalues: "{first:'value1',second:'value2',third:'value3',four:'value4',five:'value5'}"
   stringvalues: test the string in the test profile from config server
   intvaues: 20000
